# Chapter 1: Introduction to Python

The goal of this chapter is to provide the required Python programming skills to implement the algorithms in the course. We will come back to it at the beginning of every lecture, whenever new concepts are needed.

Motivations for Python:

* Python is very popular in science and engineering: check [SciPy](https://scipy.org), [scikit-learn](http://scikit-learn.org)
* Python is free software ([as in freedom](https://www.fsf.org))
* Python is portable, available for all major operating systems
* Python is a versatile language, "the second best language for everything"

Limitations relevant to this course:
* Can be slower than Matlab in some cases

Other notes:

* Python is an object-oriented language
* Python is an interpreted language

Here we focus on Python 3 (latest version is 3.7). Be careful, there are important differences between Python 3 and Python 2.

## Core Python

### Variables

Variables are typed dynamically:

In [2]:
b = 1 # b is an integer
print(b)

1


In [3]:
b = 2.0*b # now be is a float
print(b)

2.0


### Strings

In [4]:
astring = 'Hello'
another_string = ", World!"
print(astring+another_string) # Concatenation

Hello, World!


In [5]:
print(another_string[2:]) # Slicing

World!


In [6]:
print(another_string[2:-1]) # Slicing again

World


In [7]:
# Strings are immutable
astring[0]
astring[0]='h'

TypeError: 'str' object does not support item assignment

### Tuples

Tuples are sequences of arbitrary objects. They are also immutable.

In [10]:
t = (1, 'one', 'un') # this is a tuple
a, b, c = t # unpacking
print(b)

one


In [11]:
print(t[1])

one


In [12]:
words = t[1:] # slicing
print(words)

('one', 'un')


### Lists

Lists are similar to tuples but they are mutable.

In [13]:
a = [1, 'one']
a.append('un')
print(a)

[1, 'one', 'un']


In [14]:
a.insert(0, '0') # insertion
print(a)

['0', 1, 'one', 'un']


In [15]:
print(len(a)) # length

4


In [16]:
a[1:] = ['foo', 'bar', 'coin'] # slicing and modification
print(a)

['0', 'foo', 'bar', 'coin']


Lists can also be used to define matrices, but numpy arrays are much more convenient (see below).

More on [slicing](https://stackoverflow.com/questions/509211/understanding-pythons-slice-notation).

#### Exercises on slicing

Let a be a list:
1. Create a list containing all the elements in a, except the last 2.
2. Create a list containing only the first 2 elements of a, in reverse.

In [24]:
a = [1, 2, 3, 4, 5]
b = a[:-2]
print(b)

[1, 2, 3]


In [25]:
c = a[1::-1]
print(c)

[2, 1]


### References

In [27]:
# Mutable objects are references
a = ['a', 'b', 'c']
b = a # b is a reference, i.e., an 'alias' for a
b[0] = 'qwerty' # Modify b
print(a) # a is modified too

['qwerty', 'b', 'c']


In [29]:
c = a[:] # c is an independent copy of a
c[0] = 'trewq' # Modify c
print(a) # a isn't modified

['qwerty', 'b', 'c']


### Conditionals

In [30]:
# indentation is part of the language, not just style!
a = 1
if a < 0:
    print('negative')
else:
    print('positive or null')

positive or null


In [31]:
# indentation is part of the language, not just style!
a = 1
if a < 0:
    print('negative')
    else:
    print('positive or null')

SyntaxError: invalid syntax (<ipython-input-31-061c46fa1ded>, line 5)

### Error Control

Python has exception handling:

In [37]:
try:
    a = 1
    a / 0.0
except ZeroDivisionError as e:
    print("you can't do that!")

you can't do that!


### Loops

The for loop requires a sequence of elements to loop over:

In [38]:
# such as a list
a = ['a', 1, 2]
for x in a:
    print(x)

a
1
2


In [39]:
# or a sequence returned by 'range'
for i in range(5):
    print(i)

0
1
2
3
4


In [40]:
### Type conversion

In [1]:
# String to int
a = '1'
b = '2'
print(a+b)


12


In [2]:
print(int(a)+int(b))

3


### Functions

A function is defined using the 'def' keyword:

In [3]:
def my_great_function(a, b, c):
    return (a+b)*c

In [4]:
my_great_function(1, 2, 3)

9

In [5]:
def my_great_function(a, b, c, verbose=False): # last parameter has a default value
    if verbose:
        print("We will do something great")
    return (a-b)*c

In [6]:
my_great_function(1, 2, 3)

-3

In [7]:
my_great_function(1, 2, 3, True)

We will do something great


-3

### Assertions

Assertions will raise an error when their argument is False, they are a great way to safeguard your code:

In [15]:
def sqrt(x):
    assert(x>=0), "you can't do that either!"
    return x**(0.5)

In [16]:
sqrt(2)

1.4142135623730951

In [17]:
sqrt(-2)

AssertionError: you can't do that either!

### Mathematical functions

In [11]:
# Core functions
abs(-1)

1

In [12]:
max(1, 2, 3)

3

In [13]:
# Most functions are in the math module.
# A module is imported like this
import math
math.log(1)

0.0

In [57]:
# Specific functions can also be imported
from math import sin
sin(0)

0.0

In [14]:
# All the functions in a module can be imported
from math import *
cos(0)

1.0

In [18]:
# And in case of name collisions between modules, functions can also be renamed
from math import sqrt as the_right_sqrt
the_right_sqrt(-1)

ValueError: math domain error

In [19]:
sqrt(-1)

AssertionError: you can't do that either!

### Exercise: what's the value of b after my_function was called?

In [20]:
def my_function(x, y):
    x = x + y # also written x+= y
    
b = 3
my_function(b, 2)
print(b)

3


In [21]:
def my_function(x, y):
    x.append(y)
    
b = [ 3 ]
my_function(b, 2)
print(b)

[3, 2]


### $\texttt{numpy}$ Module

This module introduces array objects similar to lists, but that can be manipulated through numerous functions of the module.

The size of an array is immutable, array elements are mutable.

#### Creating an array

In [23]:
from numpy import array
a = array([1, 2, 3]) # a 1x3 array
print(a)

[1 2 3]


In [24]:
b = array([[1,2],[3,4]]) # a 2x2 array
print(b)

[[1 2]
 [3 4]]


In [25]:
from numpy import zeros
c = zeros((2,3)) # a 2x3 array filled with 0s
print(c)

[[0. 0. 0.]
 [0. 0. 0.]]


#### Modifying an array

In [26]:
c[1, 2] = 7
c[0, 0] = 9
print(c)

[[9. 0. 0.]
 [0. 0. 7.]]


In [27]:
# Slicing
c[1,:] # Access column 1

array([0., 0., 7.])

In [28]:
c[:,1] # Access row 1

array([0., 0.])

In [ ]:
c[0, 1:]

In [29]:
# Slice modification
c[:,1] = [4, 6]
print(c)

[[9. 4. 0.]
 [0. 6. 7.]]
