# Chapter 2: Systems of Linear Algebraic Equations

*Warning:* This is a critical chapter of the course.

## 2.1 Introduction

### Notation

A system of linear algebraic equations is written as follows:

$$
A_{11}x_1 + A_{12}x_2 + \ldots + A_{1n}x_n = b_1\\
A_{21}x_1 + A_{22}x_2 + \ldots + A_{2n}x_n = b_2\\
.\\
.\\
.\\
A_{n1}x_1 + A_{n2}x_2 + \ldots + A_{nn}x_n = b_n
$$

where $x_i$ are the unknowns.

It can be represented as $\textbf{Ax}=\textbf{b}$, where A is an $n \times n$ matrix, $\textbf{x}$ is a vector of n unknowns and $\textbf{b}$ is a vector of $n$ constants:

$$
    \begin{bmatrix}
        A_{11} & A_{12} & ... & A_{1n} \\
        A_{21} & A_{22} & ... & A_{2n} \\
        ...    & ...    & ... & ...    \\
        A_{n1} & A_{n2} & ... & A_{nn}
    \end{bmatrix}
    \begin{bmatrix}
    x_1\\
    x_2\\
    ...\\
    x_n
    \end{bmatrix}
    =
    \begin{bmatrix}
    b_1\\
    b_2\\
    ...\\
    b_n
    \end{bmatrix}
$$


### Uniqueness of Solution

A system of $n$ linear algebraic equations has a unique solution if and only if $\textbf{A}$ is $\textit{nonsingular}$, that is: det($\textbf{A}$) $\neq$ 0. 

#### Determinant of a Matrix

The determinant of a 2x2 matrix is defined as:

$$
\mathrm{det}(\textbf{A}) = A_{11}A_{22}-A_{12}A_{21}
$$

The determinant of a nxn matrix is defined recursively, $\forall i \leq n$: 

$$
\mathrm{det}(\textbf{A}) = \sum_{k=1}^n(-1)^{k+1}A_{ik}M_{ik}
$$

This expression is called the Laplace developement of the determinant.

The following function computes the determinant of a matrix defined in a numpy array.

In [51]:
from numpy import array
from numpy import zeros

def determinant(a):
    # Check that a is square and of size at least 2
    assert(len(a)>=2)
    assert(all(len(row) == len(a) for row in a))
    # Case n=2
    if len(a) == 2:
        return a[0][0]*a[1][1]-a[0][1]*a[1][0]
    # Other cases
    det = 0
    n = len(a)
    for k in range(n): # from 0 to n-1
        # Build M1k
        m = zeros((n-1,n-1))
        i = 0 # could be any int between 0 and n-1
        for l in range(0, n):
            if l == i: # skip row i
                continue
            for j in range(n-1):
                if j < k:
                    m[l-1][j] = a[i][j]
                else:
                    m[l-1][j] = a[i][j+1]
        det += (-1)**(k)*a[i][k]*determinant(m)
    return det


If A is singular, the system has no solution or an infinite number of solutions.

#### Example 2.1.1

Determine whether the following matrix is singular:

$$
\textbf{A}=
\begin{bmatrix}
        2.1 & -0.6 & 1.1 \\
        3.2 & 4.7 & -0.8 \\
        3.1 & -6.5 & 4.1 
    \end{bmatrix}
$$

Using our own function:

In [52]:
a = array([[2.1, -0.6, 1.1], [3.2, 4.7, -0.8], [3.1, -6.5, 4.1]])
determinant(a)

0.0

Using numpy:

In [53]:
from numpy import linalg
linalg.det(a)

0.0

Since the determinant is zero, the matrix is singular.

#### Exercice 2.1.2 (in class)

* Find examples of 2x2 and 3x3 matrices with a zero determinant.
* Find examples of systems with (1) no solution, (2) an infinite number of solutions.

### Conditioning

When the determinant of $\textbf{A}$ is "very small", small changes in the matrix result in large changes in the solution. In this case, the solution $\underline{cannot\ be\ trusted}$.

To determine whether the determinant is small, we compare it to a matrix $\textit{norm}$, for instance:

Euclidean norm:

$$
||\textbf{A}||_2 = \sqrt{\sum_{i=1}^n\sum_{j=1}^nA_{ij}^2}
$$

Row-sum norm, a.k.a the infinity norm:

$$
||\textbf{A}||_\infty=\max_{1\leq i \leq n}\sum_{j=1}^n|A_{ij}|
$$

The $\textit{condition number}$ of a matrix is defined as:

$$
\mathrm{cond}(\textbf{A}) = ||\textbf{A}||.||\textbf{A}^{-1}||
$$

If the condition number is close to unity, the matrix is well conditioned. On the contrary, a matrix with a large condition number is said to be $\textit{ill-conditioned}$.

Let's write a function to compute the condition number of a matrix:

In [56]:
def norm(a): # infinity norm
    n = 0
    for row in a:
        s = sum(abs(row))
        if s > n:
            n = s
    return n
                
def condition(a):
    from numpy.linalg import inv # this is cheating, we'll see later how to compute the inverse of a matrix
    return norm(a)*norm(inv(a))

And let's compute the condition number of the following matrix:

$$
\textbf{A}=
\begin{bmatrix}
        1 & -1.001 \\
        2.001 & -2  
    \end{bmatrix}
$$

Using our function:

In [63]:
a = array([[1, -1.001], [2.001, -2]])
condition(a)

4001.000000000308

And using numpy:

In [62]:
from numpy import inf
from numpy.linalg import cond
cond(a, p=inf)

4001.000000000308

#### Exercice 2.1.3 (in class): Effect of ill-conditioning on solutions.

1. Solve the linear system defined by $\textbf{Ax}$=$\textbf{b}$, where:
$
\textbf{A}=
\begin{bmatrix}
        1 & -1.001 \\
        2.001 & -2  
    \end{bmatrix}
$
and
$
\textbf{b}=
\begin{bmatrix}
        3 \\
        7  
    \end{bmatrix}
$


In [71]:
from numpy.linalg import solve # let's cheat for now, we'll program this in the next section

a = array([[1, -1.001], [2.001, -2]])
b = array([3, 7])
solve(a, b)

array([335.55481506, 332.22259247])

2. Solve the linear system defined by $\textbf{Ax}$=$\textbf{b}$, where:
$
\textbf{A}=
\begin{bmatrix}
        1 & -1.002 \\
        2.002 & -2  
    \end{bmatrix}
$
and
$
\textbf{b}=
\begin{bmatrix}
        3 \\
        7  
    \end{bmatrix}
$

In [72]:
from numpy.linalg import solve # let's cheat for now, we'll program this in the next section

a = array([[1, -1.002], [2.002, -2]])
solve(a, b)

array([168.88740839, 165.5562958 ])

### Methods of Solution

There are two classes of methods to solve linear systems:
* Direct methods
* Iterative methods

Direct methods work by applying the following three operations to rewrite the system in a form that permits resolution:
* Exchanging two equations
* Multiplying an equation by a nonzero constant
* Subtracting an equation from another one

Iterative methods start with an initial solution $\textbf{x}$ and refine it until convergence. Iterative methods are generally used when the matrix is very large and sparse, for instance to solve the page-rank equations.


#### Overview of Direct Methods

Direct methods are summarized in the Table below:

| Method        | Initial form    | Final form  |
| ------------- |:-------------:| -----:|
| Gauss Elimination      | $\textbf{Ax}=\textbf{b}$ | $\textbf{Ux}=\textbf{c}$ |
| LU decomposition      | $\textbf{Ax}=\textbf{b}$      |   $\textbf{LUx}=\textbf{b}$ |
| Gauss-Jordan Elimination | $\textbf{Ax}=\textbf{b}$      |    $\textbf{Ix}=\textbf{c}$ |

In this table, $\textbf{U}$ represents an upper triangular matrix, $\textbf{L}$ is a lower triangular matrix, and $\textbf{I}$ is the identity matrix. 

A square matrix is called triangular if it contains only zero elements below (upper triangular) or above (lower triangular) the diagonal. For instance, the following matrix is upper triangular:
$$
\textbf{U}=\begin{bmatrix}
1 & 2 & 3 \\
0 & 4 & 5 \\
0 & 0 & 6
\end{bmatrix}
$$
and the following matrix is lower triangular:
$$
\textbf{L}=\begin{bmatrix}
1 & 0 & 0 \\
2 & 3 & 0 \\
4 & 5 & 6
\end{bmatrix}
$$

Systems of the form $\textbf{Lx}$=$\textbf{c}$ can easily be solved by a procedure called $\textit{forward substitution}$: the first equation has only a single unknown, which is easy to solve; after solving the first equation, the second one has only one unknown remaining, and so on.

#### Exercice 2.1.4

Solve the system of linear equations defined by $\textbf{Lx}$=$\textbf{c}$, where:
$
\textbf{L}=
\begin{bmatrix}
        1 & 0 & 0 \\
        2 & 4 & 0 \\
        3 & 1  & 1
    \end{bmatrix}
$ 
and
$
\textbf{b}=
\begin{bmatrix}
        1\\
        3\\
        2
    \end{bmatrix}
$ 



In [78]:
# You can verify your solution as follows, but the point is to do it manually to understand
# how useful triangular matrices are!
from numpy.linalg import solve

a = array([[1, 0, 0], [2, 4, 0], [3, 1, 1]])
b = array([1, 3, 2])
solve(a, b)

array([ 1.  ,  0.25, -1.25])

Likewise, systems of the form $\textbf{Ux}$=$\textbf{c}$ can easily be solved by $\textit{backward substitution}$, solving the last equation first. 

Finally, systems of the form $\textbf{LUx}$=$\textbf{c}$ can quickly be solved by solving first $\textbf{Ly}$=$\textbf{c}$ by forward substitution, and then $\textbf{Ux}$=$\textbf{y}$ by backward substitution.

### Exercice 2.1.5 (Example 2.2 in textbook)

Solve the equations $\textbf{Ax}$=$\textbf{b}$, where:
$$
\textbf{A}=
\begin{bmatrix}
        8 & -6 & 2 \\
        -4 & 11 & -7 \\
        4 & -7  & 6
    \end{bmatrix}
    \quad
\textbf{b}=
\begin{bmatrix}
        28\\
        -40\\
        33
    \end{bmatrix}
$$ 
knowing that the LU decomposition of $\textbf{A}$ is (you should verify this):
$$
\textbf{A}=\textbf{LU}=
\begin{bmatrix}
        2 & 0 & 0 \\
        -1 & 2 & 0 \\
        1 & -1  & 1
    \end{bmatrix}
    \begin{bmatrix}
        4 & -3 & 1 \\
        0 & 4 & -3 \\
        0 & 0  & 2
    \end{bmatrix}
$$


## 2.2 Gauss Elimination