Important note: the solution below is here to help you verify your solution. You are supposed to be able to do this manually and obtain exact values, not numerical approximations. The exercises will be resolved manually during the tutorial.

## Exercice 1: Singular, ill-conditioned or well-conditioned

In [2]:
from numpy import array
from numpy.linalg import det
a = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(det(a)) # a is singular

0.0


In [3]:
b = array([[2, -2, 1], [1, 0, -1], [4, 1, 1]])
print(det(b)) # b is well-conditioned

13.000000000000005


In [4]:
c = array([[1, 2.0001, 3], [4, 5, 6], [7, 8, 9]])
print(det(c)) # c is ill-conditioned

0.0006000000000018899


## Exercice 2: LU decomposition

In [12]:
from numpy import array, dot
a = array([[2, -2, 1], [1, 0, -1], [4, 1, 1]])
u = array([[2, -2, 1], [0, 1, -3/2], [0, 0, 13/2]])
l = array([[1, 0, 0], [1/2, 1, 0], [2, 5, 1]])
print("L={}".format(l))
print("U={}".format(u))
# Verification
dot(l, u)

L=[[1.  0.  0. ]
 [0.5 1.  0. ]
 [2.  5.  1. ]]
U=[[ 2.  -2.   1. ]
 [ 0.   1.  -1.5]
 [ 0.   0.   6.5]]


array([[ 2., -2.,  1.],
       [ 1.,  0., -1.],
       [ 4.,  1.,  1.]])

## Exercice 3: Resolution using LU decomposition

In [14]:
b = array([1, 2, 0])
from numpy.linalg import solve
solve(a, b)

array([ 0.53846154, -0.69230769, -1.46153846])

## Exercice 4: Gauss elimination

In [20]:
from numpy import array, transpose
from numpy.linalg import solve
a = array([[0, 1, 4], [2, 0, 7], [1, 4, 0]])
b = transpose(array([[-1, 6, 0], [3, 2, 1]]))
solve(a, b)

array([[ 3.17948718, -1.15384615],
       [-0.79487179,  0.53846154],
       [-0.05128205,  0.61538462]])

## Exercice 5: Condition number

cond(A) = $||A||_\infty||A^{-1}||_\infty$

In [33]:
from numpy import array, inf
a = array([[2, -2, 1], [1, 0, -1], [4, 1, 1]])
from numpy.linalg import cond
cond(a, p=inf)

5.999999999999999

## Exercice 6: Matrix inversion

In [23]:
from numpy import array
from numpy.linalg import inv
a = array([[3, 1, 2],[1, 1, 0],[5, 8, 9]])
inv(a)

array([[ 0.375     ,  0.29166667, -0.08333333],
       [-0.375     ,  0.70833333,  0.08333333],
       [ 0.125     , -0.79166667,  0.08333333]])

## Exercice 7: Cholesky decomposition

In [29]:
from numpy import array
from numpy.linalg import cholesky
a = array([[1, 1, 1], [1, 2, 2], [1, 2, 3]])
inv(a)
cholesky(a)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])